### ISSUE TITLE
Add SOA-EDIT-API option to manage domain page

### ISSUE THREAD

**Issue by ScottyTM** [thomasDOTde/PowerDNS-Admin#28]
I would like to be able to change the setting for SOA serial updates for existing domains and not only for new domains.

The changes were added with this commit:

https://github.com/ngoduykhanh/PowerDNS-Admin/commit/a4df1e47fe92504006f9f487ebe1a181e37a3d2a

**Comment by thomasDOTwtf** [comment]
Please test from current master. Features is implemented.
Can be found on Admin page of each domain.

**Comment by akurach** [comment]
> Please test from current master. Features is implemented.

It just broke domain manage page) 

```
[INFO] 10.4.3.45 - - [28/Mar/2018 14:26:53] "GET /admin/domain/example.com/manage HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/pdns-web/PowerDNS-Admin/app/views.py", line 131, in decorated_function
    return f(*args, **kwargs)
  File "/opt/pdns-web/PowerDNS-Admin/app/views.py", line 551, in domain_management
    return render_template('domain_management.html', domain=domain, users=users, domain_user_ids=domain_user_ids)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/pdns-web/PowerDNS-Admin/app/templates/domain_management.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/pdns-web/PowerDNS-Admin/app/templates/base.html", line 141, in top-level template code
    {% block dashboard_stat %}
  File "/opt/pdns-web/PowerDNS-Admin/app/templates/domain_management.html", line 6, in block "dashboard_stat"
    {% if status['status'] == 'ok' %}
  File "/opt/pdns-web/flask/lib/python2.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
UndefinedError: 'status' is undefined
```

**Comment by thomasDOTwtf** [comment]
Hey, thanks for your feedback. Should be fixed.
Can you give it a try with a pull from master?

**Comment by akurach** [comment]
> Can you give it a try with a pull from master?

Confirm, Works! 
thx!

**Comment by ScottyTM** [comment]
Could you also show the current setting on the Admin page? It's available in the domain metadate over the API.
